export type TermsSection = {
  number: number;
  title: string;
  paragraphs: string[];
};

export type TermsOfUseContent = {
  lastUpdated: string;
  title: string;
  intro: string[];
  sections: TermsSection[];
};

export const termsOfUseContent: Record<"en" | "tr", TermsOfUseContent> = {
  en: {
    lastUpdated: "March 8, 2026",
    title: "Terms of Use",
    intro: [
      'These Terms of Use ("Terms") govern your access to and use of the websites, web applications, mobile applications, software, AI-powered features, content, and related services made available by BMNova, operated by Ali Mertcan Karaman ("BMNova," "we," "us," or "our").',
      "By accessing or using BMNova's services, you agree to these Terms. If you do not agree, you should not use the services.",
    ],
    sections: [
      {
        number: 1,
        title: "Who We Are",
        paragraphs: [
          "BMNova",
          "Operated by Ali Mertcan Karaman",
          "OSTİM OSB Mah. Cevat Dündar Cad. No: 1/1 İç Kapı No: 10",
          "Yenimahalle / Ankara, Türkiye",
          "Email: contact@bmnova.com",
          "Website: https://www.bmnova.com/",
        ],
      },
      {
        number: 2,
        title: "Scope",
        paragraphs: [
          "These Terms apply to your use of:",
          "our website;",
          "our web applications and SaaS products;",
          "our mobile applications;",
          "our AI-powered tools and features;",
          "paid subscriptions, one-time purchases, upgrades, credits, and premium features;",
          "related support, communications, and updates.",
          "Some services may be subject to additional product-specific terms, campaign rules, platform terms, or app store rules. If there is a conflict, the more specific terms will apply for that service.",
        ],
      },
      {
        number: 3,
        title: "Eligibility",
        paragraphs: [
          "You may use the services only if you are legally capable of entering into a binding agreement under applicable law.",
          "If you use the services on behalf of a company, organization, or another legal entity, you represent that you have authority to bind that entity to these Terms.",
          "If you are below the age required to enter into these Terms on your own under applicable law, you may use the services only with the involvement of a parent or legal guardian.",
        ],
      },
      {
        number: 4,
        title: "Accounts",
        paragraphs: [
          "Some features may require you to create an account.",
          "You agree to provide accurate, current, and complete information and to keep it up to date. You are responsible for:",
          "keeping your credentials confidential;",
          "all activity under your account;",
          "informing us promptly if you suspect unauthorized access or misuse.",
          "We may suspend or terminate accounts that are inaccurate, insecure, abusive, unlawful, or used in violation of these Terms.",
        ],
      },
      {
        number: 5,
        title: "Our Services",
        paragraphs: [
          "BMNova develops and operates mobile apps, web products, SaaS platforms, and AI-enabled software.",
          "Our services may include:",
          "creation, editing, automation, enhancement, or analysis tools;",
          "AI-assisted workflows and generated outputs;",
          "dashboards, subscriptions, feature entitlements, or usage-based tools;",
          "integrations with third-party infrastructure, billing, analytics, authentication, or AI providers.",
          "We may modify, improve, remove, suspend, or update parts of the services at any time for business, legal, security, technical, or product reasons.",
        ],
      },
      {
        number: 6,
        title: "Acceptable Use",
        paragraphs: [
          "You may use the services only in compliance with these Terms and applicable law.",
          "You must not:",
          "use the services for unlawful, harmful, fraudulent, deceptive, or abusive purposes;",
          "infringe the rights of others;",
          "upload or submit content that you do not have the right to use;",
          "interfere with, disrupt, damage, or compromise the services;",
          "attempt to reverse engineer, bypass restrictions, or access non-public parts of the services without authorization;",
          "use automated means to scrape, extract, or harvest data except where expressly permitted;",
          "upload malware, malicious code, or harmful content;",
          "use the services to generate, distribute, or facilitate illegal or prohibited content;",
          "misuse AI-enabled features in a way that is unlawful, misleading, or harmful.",
          "We may monitor compliance, investigate misuse, and suspend or terminate access where necessary to protect users, BMNova, or third parties.",
        ],
      },
      {
        number: 7,
        title: "User Content",
        paragraphs: [
          'You may be able to upload, submit, store, process, create, or share text, images, audio, video, prompts, documents, datasets, or other materials through the services ("User Content").',
          "You retain ownership of your User Content, except where ownership does not apply under law.",
          "You grant BMNova a limited, non-exclusive, worldwide, royalty-free license to host, store, reproduce, process, transmit, display, and use your User Content only as reasonably necessary to:",
          "provide and operate the services;",
          "process your requests and generate outputs;",
          "maintain security and prevent abuse;",
          "troubleshoot, support, and improve service reliability;",
          "comply with legal obligations and enforce these Terms.",
          "This license continues only for as long as needed for those purposes, subject to backup retention, technical limitations, legal obligations, and dispute resolution needs.",
          "You represent and warrant that:",
          "you have the necessary rights and permissions to provide the User Content;",
          "your User Content and your use of it through the services do not violate law or third-party rights;",
          "your User Content does not include material you are prohibited from submitting.",
        ],
      },
      {
        number: 8,
        title: "AI Features and Outputs",
        paragraphs: [
          "Some BMNova services include AI-powered or machine-assisted functionality.",
          "By using those features, you understand and agree that:",
          "outputs may be incomplete, inaccurate, inconsistent, or unsuitable for your intended use;",
          "you are responsible for reviewing outputs before relying on, publishing, sharing, or acting on them;",
          "AI-generated content is provided for convenience and productivity, not as guaranteed fact or professional advice;",
          "the services should not be used as a substitute for legal, medical, financial, compliance, employment, or other regulated professional advice.",
          "You are responsible for ensuring that your inputs and your use of outputs comply with applicable law and third-party rights.",
          "As between you and BMNova, and subject to applicable law and third-party rights, you may use outputs generated for you through the services for lawful purposes unless product-specific terms state otherwise.",
          "BMNova does not guarantee that outputs will be unique, and similar or identical outputs may be generated for other users.",
        ],
      },
      {
        number: 9,
        title: "No Training on Your Content",
        paragraphs: [
          "At this time, BMNova does not use your prompts, uploads, outputs, or client content to train or improve general-purpose AI models.",
          "We may process such content only to provide the requested service, maintain security, prevent abuse, troubleshoot issues, comply with law, and enforce these Terms.",
        ],
      },
      {
        number: 10,
        title: "Third-Party Services",
        paragraphs: [
          "Our services may depend on or integrate with third-party services, including cloud providers, app stores, payment providers, AI providers, analytics tools, communication tools, and authentication systems.",
          "Those third-party services may be governed by their own terms and privacy policies. BMNova is not responsible for third-party services except to the extent required by applicable law.",
        ],
      },
      {
        number: 11,
        title: "Payments, Billing, and Subscriptions",
        paragraphs: [
          "Some services are free, while others require payment.",
          "Paid services may be offered as recurring subscriptions, one-time purchases, prepaid credits, upgrades, or premium access.",
          "Prices, billing periods, included features, renewal terms, and taxes will generally be shown at the point of purchase or in the relevant product interface.",
          "Web payments: For certain web-based products or subscriptions, payments may be processed through third-party billing providers such as Paddle or another authorized payment partner. Where a billing provider or merchant of record handles checkout, that provider may process payments, invoices, taxes, renewals, and certain refund requests under its own terms and policies.",
          "Mobile app payments: For mobile apps, subscriptions and in-app purchases may be processed through the Apple App Store, Google Play, or related subscription infrastructure providers used by BMNova, such as RevenueCat or Adapty, depending on the product. Where purchases are made through an app store, billing, renewals, cancellations, and refund handling are generally governed by the applicable platform rules and your agreement with that platform.",
          "Renewals and cancellation: Unless stated otherwise, recurring subscriptions renew automatically until canceled. You can cancel before the next renewal date through the relevant billing portal, product interface, or app store account settings. Canceling stops future renewals but does not automatically create a refund for past charges unless required by law or stated in the applicable billing terms.",
          "Refunds: Except where required by law or provided in a product-specific refund policy, fees are generally non-refundable. If your purchase was processed by a billing provider or app store, you may need to request a refund through that provider first.",
          "Failed payments: If a payment fails, we or the relevant billing provider may retry the charge, suspend paid access, downgrade your plan, or cancel the relevant subscription until payment is resolved.",
        ],
      },
      {
        number: 12,
        title: "Trials, Promotions, and Credits",
        paragraphs: [
          "We may offer free trials, discounts, promotions, beta access, referral benefits, or prepaid credits.",
          "Unless stated otherwise:",
          "they may be modified or withdrawn at any time;",
          "they may not be combined with other offers;",
          "they may be subject to eligibility limits;",
          "credits may expire and have no cash value unless required by law;",
          "abuse of promotional systems may result in suspension or termination.",
          "If a trial converts into a paid subscription, you will be charged according to the terms shown when you enrolled unless you cancel in time.",
        ],
      },
      {
        number: 13,
        title: "Beta and Experimental Features",
        paragraphs: [
          "Some features may be marked as beta, preview, early access, or experimental.",
          "These features may be incomplete, unstable, changed without notice, or unavailable at any time. They are provided on a testing basis and may be subject to additional restrictions.",
        ],
      },
      {
        number: 14,
        title: "Intellectual Property",
        paragraphs: [
          "The services, including software, code, interfaces, visual elements, designs, branding, logos, text, graphics, layouts, and other content provided by BMNova, are owned by BMNova or its licensors and are protected by applicable intellectual property laws.",
          "Except as expressly permitted in these Terms, you may not:",
          "copy, reproduce, modify, distribute, sell, sublicense, or commercially exploit the services;",
          "remove copyright, trademark, or proprietary notices;",
          "use BMNova branding without prior written permission;",
          "access or use the services to build a competing product or service in a manner prohibited by law.",
          "Subject to these Terms, BMNova grants you a limited, non-exclusive, non-transferable, revocable right to use the services for their intended purpose.",
        ],
      },
      {
        number: 15,
        title: "Feedback",
        paragraphs: [
          "If you send us suggestions, ideas, feature requests, bug reports, or other feedback, you grant BMNova a non-exclusive, worldwide, royalty-free license to use, reproduce, adapt, publish, and incorporate that feedback without compensation or restriction.",
        ],
      },
      {
        number: 16,
        title: "Availability and Changes",
        paragraphs: [
          "We do not guarantee that the services will always be available, uninterrupted, secure, or error-free.",
          "We may:",
          "modify or discontinue features;",
          "impose usage limits;",
          "update technical requirements;",
          "suspend access for maintenance, legal, security, operational, or product reasons.",
          "To the extent permitted by law, BMNova is not liable for losses caused by downtime, delay, interruption, or feature changes.",
        ],
      },
      {
        number: 17,
        title: "Suspension and Termination",
        paragraphs: [
          "We may suspend or terminate your access immediately or at any time if:",
          "you violate these Terms;",
          "you create legal, security, or operational risk;",
          "we suspect fraud, abuse, or unauthorized activity;",
          "we are required to do so by law or by a third-party platform/provider;",
          "payment obligations remain unresolved where applicable.",
          "You may stop using the services at any time and may cancel any recurring subscription in accordance with the relevant billing flow.",
          "Upon termination, your right to use the services ends immediately. Provisions that by their nature should survive termination will continue to apply, including provisions relating to payments owed, intellectual property, disclaimers, limitations of liability, disputes, and enforcement.",
        ],
      },
      {
        number: 18,
        title: "Disclaimers",
        paragraphs: [
          'To the maximum extent permitted by applicable law, the services are provided on an "as is" and "as available" basis.',
          "BMNova does not guarantee that the services will be uninterrupted, error-free, secure, or suitable for every intended purpose. To the maximum extent permitted by law, BMNova disclaims warranties of merchantability, fitness for a particular purpose, non-infringement, and accuracy.",
          "Without limiting the above, BMNova does not warrant that:",
          "the services will meet your requirements or expectations;",
          "the services will always be available, uninterrupted, timely, secure, or error-free;",
          "any output, recommendation, analysis, or AI-generated result will be accurate, complete, reliable, lawful, or fit for a particular purpose;",
          "defects will always be corrected; or",
          "the services will be free from all harmful components.",
          "Nothing in this section limits any non-waivable rights you may have under applicable consumer law.",
        ],
      },
      {
        number: 19,
        title: "Limitation of Liability",
        paragraphs: [
          "To the maximum extent permitted by applicable law, BMNova and its affiliates, contractors, licensors, service providers, and representatives will not be liable for any indirect, incidental, special, consequential, or punitive damages, or for any loss of profit, revenue, business, goodwill, data, or opportunity, arising out of or related to your use of, or inability to use, the services.",
          "To the maximum extent permitted by applicable law, BMNova's total aggregate liability for all claims arising out of or relating to the services or these Terms will not exceed the amount you paid to BMNova for the relevant paid service during the 12 months before the event giving rise to the claim.",
          "Nothing in these Terms excludes or limits liability that cannot be excluded or limited under applicable law.",
        ],
      },
      {
        number: 20,
        title: "Responsibility for Your Use of the Services",
        paragraphs: [
          "You are responsible for your use of the services, your User Content, and your compliance with these Terms and applicable law.",
          "To the maximum extent permitted by law, if a third party brings a claim against BMNova arising directly from:",
          "content you submit or upload;",
          "your unlawful use of the services; or",
          "your violation of these Terms or infringement of a third party's rights,",
          "you agree to be responsible for the resulting losses, costs, or expenses reasonably incurred by BMNova, to the extent caused by your actions.",
          "Nothing in this section applies to the extent a claim results from BMNova's own unlawful conduct, gross negligence, or willful misconduct.",
        ],
      },
      {
        number: 21,
        title: "Export, Sanctions, and Compliance",
        paragraphs: [
          "You may not use the services in violation of export control, sanctions, or other applicable trade laws.",
          "You represent that you are not using the services in a way that would violate applicable restrictions or laws.",
        ],
      },
      {
        number: 22,
        title: "Privacy",
        paragraphs: [
          "Your use of the services is also subject to our Privacy Policy, which explains how we process personal data.",
        ],
      },
      {
        number: 23,
        title: "App Store Terms",
        paragraphs: [
          "If you download or use a BMNova mobile app through Apple's App Store or Google Play, you acknowledge that:",
          "these Terms are between you and BMNova, not Apple or Google, except where platform rules state otherwise;",
          "Apple and Google are not responsible for the app's maintenance or support except as required by their own terms or applicable law;",
          "your use of the app must comply with the rules of the relevant app store.",
        ],
      },
      {
        number: 24,
        title: "Governing Law and Disputes",
        paragraphs: [
          "These Terms are governed by the laws of Türkiye, excluding conflict of law principles, unless mandatory consumer law in your country of residence requires otherwise.",
          "Any dispute arising out of or relating to these Terms or the services will be subject to the competent courts and enforcement offices of Ankara, Türkiye, unless applicable law requires a different forum.",
          "If you are a consumer and mandatory law gives you the right to bring claims in your place of residence, those rights remain unaffected.",
        ],
      },
      {
        number: 25,
        title: "Changes to These Terms",
        paragraphs: [
          "We may update these Terms from time to time.",
          'When we do, we will update the "Last updated" date above. If changes are material, we may also provide additional notice through the website, app, email, or product interface.',
          "By continuing to use the services after updated Terms become effective, you agree to the revised Terms.",
        ],
      },
      {
        number: 26,
        title: "General",
        paragraphs: [
          "If any provision of these Terms is found unenforceable, the remaining provisions will remain in full force.",
          "Our failure to enforce any provision is not a waiver of that provision.",
          "You may not assign these Terms without our prior written consent. We may assign these Terms in connection with a merger, acquisition, restructuring, sale of assets, or by operation of law.",
          "These Terms, together with any additional product terms, pricing terms, and policies incorporated by reference, form the entire agreement between you and BMNova regarding the services.",
        ],
      },
      {
        number: 27,
        title: "Contact",
        paragraphs: [
          "For questions about these Terms, contact:",
          "BMNova",
          "Operated by Ali Mertcan Karaman",
          "OSTİM OSB Mah. Cevat Dündar Cad. No: 1/1 İç Kapı No: 10",
          "Yenimahalle / Ankara, Türkiye",
          "contact@bmnova.com",
        ],
      },
    ],
  },
  tr: {
    lastUpdated: "8 Mart 2026",
    title: "Kullanım Koşulları",
    intro: [
      'İşbu Kullanım Koşulları ("Koşullar"), Ali Mertcan Karaman tarafından işletilen BMNova\'nın ("BMNova", "biz", "bize" veya "bizim") sunduğu web siteleri, web uygulamaları, mobil uygulamalar, yazılımlar, yapay zekâ destekli özellikler, içerikler ve ilgili hizmetlere erişiminizi ve bunları kullanımınızı düzenler.',
      "BMNova hizmetlerine erişerek veya bunları kullanarak bu Koşullar'ı kabul etmiş olursunuz. Kabul etmiyorsanız hizmetleri kullanmamalısınız.",
    ],
    sections: [
      {
        number: 1,
        title: "Biz Kimiz",
        paragraphs: [
          "BMNova",
          "İşleten: Ali Mertcan Karaman",
          "OSTİM OSB Mah. Cevat Dündar Cad. No: 1/1 İç Kapı No: 10",
          "Yenimahalle / Ankara, Türkiye",
          "E-posta: contact@bmnova.com",
          "Web sitesi: https://www.bmnova.com/",
        ],
      },
      {
        number: 2,
        title: "Kapsam",
        paragraphs: [
          "Bu Koşullar aşağıdakilerin kullanımına uygulanır:",
          "web sitemiz;",
          "web uygulamalarımız ve SaaS ürünlerimiz;",
          "mobil uygulamalarımız;",
          "yapay zekâ destekli araçlarımız ve özelliklerimiz;",
          "ücretli abonelikler, tek seferlik satın alımlar, yükseltmeler, krediler ve premium özellikler;",
          "bunlarla bağlantılı destek, iletişim ve güncellemeler.",
          "Bazı hizmetler ek ürün koşullarına, kampanya kurallarına, platform şartlarına veya uygulama mağazası kurallarına tabi olabilir. Çelişki olması halinde ilgili hizmet için daha özel düzenleme uygulanır.",
        ],
      },
      {
        number: 3,
        title: "Uygunluk",
        paragraphs: [
          "Hizmetleri yalnızca yürürlükteki hukuka göre bağlayıcı bir sözleşme kurma ehliyetine sahipseniz kullanabilirsiniz.",
          "Hizmetleri bir şirket, kurum veya başka bir tüzel kişi adına kullanıyorsanız, o kurumu bu Koşullar ile bağlama yetkiniz olduğunu beyan edersiniz.",
          "Uygulanabilir hukuk uyarınca bu Koşullar'ı tek başınıza kabul etmek için gerekli yaşın altındaysanız, hizmetleri yalnızca ebeveyn veya yasal temsilci katılımıyla kullanabilirsiniz.",
        ],
      },
      {
        number: 4,
        title: "Hesaplar",
        paragraphs: [
          "Bazı özellikler bir hesap oluşturmanızı gerektirebilir.",
          "Doğru, güncel ve eksiksiz bilgi sağlamayı ve gerektiğinde güncellemeyi kabul edersiniz. Şunlardan siz sorumlusunuz:",
          "hesap bilgilerinizin ve şifrelerinizin gizliliğini korumaktan;",
          "hesabınız altında gerçekleşen tüm faaliyetlerden;",
          "yetkisiz erişim veya kötüye kullanım şüphesi halinde bizi gecikmeden bilgilendirmekten.",
          "Yanıltıcı, güvensiz, kötüye kullanılan, hukuka aykırı veya bu Koşullar'a aykırı kullanılan hesapları askıya alabilir veya kapatabiliriz.",
        ],
      },
      {
        number: 5,
        title: "Hizmetlerimiz",
        paragraphs: [
          "BMNova mobil uygulamalar, web ürünleri, SaaS platformları ve yapay zekâ destekli yazılımlar geliştirir ve işletir.",
          "Hizmetlerimiz şunları içerebilir:",
          "içerik üretimi, düzenleme, otomasyon, geliştirme veya analiz araçları;",
          "yapay zekâ destekli iş akışları ve üretilen çıktılar;",
          "paneller, abonelikler, özellik erişimleri veya kullanıma bağlı araçlar;",
          "üçüncü taraf altyapı, ödeme, analiz, kimlik doğrulama veya yapay zekâ sağlayıcılarıyla entegrasyonlar.",
          "Hizmetlerin bazı bölümlerini ticari, hukuki, güvenlik, teknik veya ürünle ilgili nedenlerle dilediğimiz zaman değiştirebilir, geliştirebilir, kaldırabilir, askıya alabilir veya güncelleyebiliriz.",
        ],
      },
      {
        number: 6,
        title: "Kabul Edilebilir Kullanım",
        paragraphs: [
          "Hizmetleri yalnızca bu Koşullar'a ve yürürlükteki hukuka uygun şekilde kullanabilirsiniz.",
          "Şunları yapmamalısınız:",
          "hizmetleri hukuka aykırı, zararlı, dolandırıcı, aldatıcı veya kötüye kullanıma yönelik amaçlarla kullanmak;",
          "başkalarının haklarını ihlal etmek;",
          "kullanma hakkınız olmayan içerikleri yüklemek veya göndermek;",
          "hizmetlere müdahale etmek, bozmak, zarar vermek veya güvenliğini tehlikeye atmak;",
          "tersine mühendislik yapmak, kısıtlamaları aşmaya çalışmak veya yetkisiz şekilde herkese açık olmayan bölümlere erişmek;",
          "açıkça izin verilmedikçe otomatik araçlarla veri çekmek, toplamak veya kazımak;",
          "kötü amaçlı yazılım, zararlı kod veya tehlikeli içerik yüklemek;",
          "hizmetleri hukuka aykırı veya yasak içerik üretmek, yaymak veya kolaylaştırmak için kullanmak;",
          "yapay zekâ destekli özellikleri hukuka aykırı, yanıltıcı veya zararlı biçimde kötüye kullanmak.",
          "Uygunluğu izleyebilir, kötüye kullanımı inceleyebilir ve kullanıcıları, BMNova'yı veya üçüncü tarafları korumak için erişimi askıya alabilir ya da sonlandırabiliriz.",
        ],
      },
      {
        number: 7,
        title: "Kullanıcı İçeriği",
        paragraphs: [
          "Hizmetler üzerinden metin, görsel, ses, video, komut, belge, veri seti veya diğer materyalleri yükleyebilir, gönderebilir, depolayabilir, işleyebilir, oluşturabilir veya paylaşabilirsiniz (\"Kullanıcı İçeriği\").",
          "Hukuken aksi gerekmediği sürece Kullanıcı İçeriğiniz üzerindeki mülkiyet sizde kalır.",
          "BMNova'ya, Kullanıcı İçeriğinizi yalnızca aşağıdaki amaçlar için makul ölçüde gerekli olduğu kadar barındırmak, depolamak, çoğaltmak, işlemek, iletmek, görüntülemek ve kullanmak üzere sınırlı, münhasır olmayan, dünya çapında ve bedelsiz bir lisans vermiş olursunuz:",
          "hizmetleri sunmak ve işletmek;",
          "taleplerinizi işlemek ve çıktı üretmek;",
          "güvenliği sağlamak ve kötüye kullanımı önlemek;",
          "hata ayıklamak, destek sunmak ve hizmet güvenilirliğini artırmak;",
          "hukuki yükümlülüklere uymak ve bu Koşullar'ı uygulamak.",
          "Bu lisans yalnızca bu amaçlar için gerekli olduğu süre boyunca geçerlidir; yedekleme süreçleri, teknik sınırlamalar, hukuki yükümlülükler ve uyuşmazlık çözümü ihtiyaçları saklıdır.",
          "Şunları beyan ve taahhüt edersiniz:",
          "Kullanıcı İçeriğini sağlamak için gerekli haklara ve izinlere sahip olduğunuzu;",
          "Kullanıcı İçeriğinizin ve onu hizmetler üzerinden kullanmanızın hukuku veya üçüncü taraf haklarını ihlal etmediğini;",
          "göndermeniz yasak olan materyalleri sağlamadığınızı.",
        ],
      },
      {
        number: 8,
        title: "Yapay Zekâ Özellikleri ve Çıktılar",
        paragraphs: [
          "Bazı BMNova hizmetleri yapay zekâ destekli veya makine destekli işlevler içerir.",
          "Bu özellikleri kullanarak şunları kabul etmiş olursunuz:",
          "çıktılar eksik, hatalı, tutarsız veya amacınıza uygun olmayabilir;",
          "çıktılara güvenmeden, yayımlamadan, paylaşmadan veya bunlara dayanarak işlem yapmadan önce bunları gözden geçirmek sizin sorumluluğunuzdadır;",
          "yapay zekâ tarafından üretilen içerik kolaylık ve verimlilik amacıyla sunulur; garanti edilmiş gerçeklik veya profesyonel görüş değildir;",
          "hizmetler hukuki, tıbbi, mali, uyum, istihdam veya benzeri düzenlemeye tabi profesyonel danışmanlığın yerine kullanılmamalıdır.",
          "Girdilerinizin ve çıktıları kullanımınızın yürürlükteki hukuka ve üçüncü taraf haklarına uygun olmasından siz sorumlusunuz.",
          "Sizinle BMNova arasındaki ilişkide ve uygulanabilir hukuk ile üçüncü taraf hakları saklı kalmak üzere, ürün bazlı ek şartlarda aksi belirtilmedikçe sizin için üretilen çıktıları hukuka uygun amaçlarla kullanabilirsiniz.",
          "BMNova, çıktılarının benzersiz olacağını garanti etmez; benzer veya aynı çıktılar başka kullanıcılar için de üretilebilir.",
        ],
      },
      {
        number: 9,
        title: "İçeriğinizin Eğitim İçin Kullanılmaması",
        paragraphs: [
          "BMNova şu anda komutlarınızı, yüklemelerinizi, çıktılarınızı veya müşteri içeriklerini genel amaçlı yapay zekâ modellerini eğitmek ya da geliştirmek için kullanmamaktadır.",
          "Bu içerikler yalnızca talep edilen hizmeti sunmak, güvenliği sağlamak, kötüye kullanımı önlemek, sorun gidermek, hukuka uymak ve bu Koşullar'ı uygulamak amacıyla işlenebilir.",
        ],
      },
      {
        number: 10,
        title: "Üçüncü Taraf Hizmetler",
        paragraphs: [
          "Hizmetlerimiz; bulut sağlayıcıları, uygulama mağazaları, ödeme sağlayıcıları, yapay zekâ sağlayıcıları, analiz araçları, iletişim araçları ve kimlik doğrulama sistemleri gibi üçüncü taraf hizmetlere dayanabilir veya bunlarla entegre olabilir.",
          "Bu üçüncü taraf hizmetler kendi koşullarına ve gizlilik politikalarına tabi olabilir. BMNova, uygulanabilir hukukun gerektirdiği haller dışında, üçüncü taraf hizmetlerden sorumlu değildir.",
        ],
      },
      {
        number: 11,
        title: "Ödemeler, Faturalama ve Abonelikler",
        paragraphs: [
          "Bazı hizmetler ücretsizdir, bazıları ise ücretlidir.",
          "Ücretli hizmetler; yinelenen abonelik, tek seferlik satın alma, ön ödemeli kredi, yükseltme veya premium erişim şeklinde sunulabilir.",
          "Fiyatlar, fatura dönemleri, dahil olan özellikler, yenileme koşulları ve vergiler genellikle satın alma anında veya ilgili ürün arayüzünde gösterilir.",
          "Web ödemeleri: Bazı web tabanlı ürünler veya abonelikler için ödemeler Paddle veya başka yetkili ödeme/abonelik iş ortakları aracılığıyla işlenebilir. Ödeme sağlayıcısı veya merchant of record modeli kullanılıyorsa, ödeme işlemleri, faturalar, vergiler, yenilemeler ve bazı iade talepleri ilgili sağlayıcının kendi koşulları ve politikaları kapsamında yürütülebilir.",
          "Mobil uygulama ödemeleri: Mobil uygulamalarda abonelikler ve uygulama içi satın alımlar; ürünün yapısına göre Apple App Store, Google Play veya BMNova'nın kullandığı RevenueCat ya da Adapty gibi abonelik altyapıları üzerinden yönetilebilir. Satın alma uygulama mağazası üzerinden yapıldıysa, faturalama, yenileme, iptal ve iade süreçleri genel olarak ilgili platform kurallarına ve o platformla yaptığınız sözleşmeye tabidir.",
          "Yenileme ve iptal: Aksi belirtilmedikçe, yinelenen abonelikler iptal edilene kadar otomatik yenilenir. Bir sonraki yenileme tarihinden önce ilgili ödeme paneli, ürün arayüzü veya uygulama mağazası hesap ayarlarınız üzerinden iptal edebilirsiniz. İptal işlemi gelecekteki yenilemeleri durdurur; geçmiş ödemeler için otomatik iade hakkı doğurmaz. Yasal zorunluluklar veya ilgili ödeme koşulları saklıdır.",
          "İadeler: Kanunen gerekmedikçe veya ürün bazlı özel bir iade politikası bulunmadıkça ücretler genel olarak iade edilmez. Ödemeniz bir ödeme sağlayıcısı veya uygulama mağazası üzerinden işlendiysa, iade talebinizi öncelikle ilgili sağlayıcıya yönlendirmeniz gerekebilir.",
          "Başarısız ödemeler: Ödeme başarısız olursa, biz veya ilgili ödeme sağlayıcısı tahsilatı yeniden deneyebilir, ücretli erişimi askıya alabilir, planınızı düşürebilir veya ödeme çözülene kadar ilgili aboneliği iptal edebilir.",
        ],
      },
      {
        number: 12,
        title: "Denemeler, Kampanyalar ve Krediler",
        paragraphs: [
          "Ücretsiz denemeler, indirimler, kampanyalar, beta erişimi, tavsiye avantajları veya ön ödemeli krediler sunabiliriz.",
          "Aksi belirtilmedikçe:",
          "bunlar her zaman değiştirilebilir veya sona erdirilebilir;",
          "başka tekliflerle birleştirilemeyebilir;",
          "uygunluk koşullarına tabi olabilir;",
          "krediler süresi dolabilen ve nakde çevrilemeyen haklar olabilir;",
          "kampanya sistemlerinin kötüye kullanımı hesabın askıya alınmasına veya sonlandırılmasına yol açabilir.",
          "Ücretsiz deneme ücretli aboneliğe dönüşüyorsa, zamanında iptal etmediğiniz sürece kayıt sırasında gösterilen koşullara göre ücretlendirilirsiniz.",
        ],
      },
      {
        number: 13,
        title: "Beta ve Deneysel Özellikler",
        paragraphs: [
          "Bazı özellikler beta, ön izleme, erken erişim veya deneysel olarak işaretlenebilir.",
          "Bu özellikler eksik olabilir, kararsız çalışabilir, önceden bildirim yapılmadan değiştirilebilir veya tamamen kaldırılabilir. Test niteliğinde sunulurlar ve ek kısıtlamalara tabi olabilirler.",
        ],
      },
      {
        number: 14,
        title: "Fikri Mülkiyet",
        paragraphs: [
          "Hizmetler; yazılım, kod, arayüz, görsel öğeler, tasarımlar, marka unsurları, logolar, metinler, grafikler, yerleşimler ve BMNova tarafından sağlanan diğer içerikler dahil olmak üzere BMNova'ya veya lisans verenlerine aittir ve uygulanabilir fikri mülkiyet mevzuatı ile korunur.",
          "Bu Koşullar'da açıkça izin verilmedikçe şunları yapamazsınız:",
          "hizmetleri kopyalamak, çoğaltmak, değiştirmek, dağıtmak, satmak, alt lisanslamak veya ticari olarak kullanmak;",
          "telif hakkı, marka veya mülkiyet bildirimlerini kaldırmak;",
          "BMNova markasını önceden yazılı izin olmadan kullanmak;",
          "hukuken yasak şekilde rekabet eden bir ürün veya hizmet geliştirmek için hizmetlere erişmek veya bunları kullanmak.",
          "Bu Koşullar'a tabi olarak BMNova size hizmetleri amaçlarına uygun şekilde kullanmanız için sınırlı, münhasır olmayan, devredilemez ve geri alınabilir bir kullanım hakkı verir.",
        ],
      },
      {
        number: 15,
        title: "Geri Bildirim",
        paragraphs: [
          "Bize öneri, fikir, özellik talebi, hata bildirimi veya başka türde geri bildirim gönderirseniz, BMNova'ya bunları herhangi bir bedel veya kısıtlama olmaksızın kullanma, çoğaltma, uyarlama, yayımlama ve ürünlerine dahil etme hakkını vermiş olursunuz.",
        ],
      },
      {
        number: 16,
        title: "Erişilebilirlik ve Değişiklikler",
        paragraphs: [
          "Hizmetlerin her zaman erişilebilir, kesintisiz, güvenli veya hatasız olacağını garanti etmiyoruz.",
          "Şunları yapabiliriz:",
          "özellikleri değiştirmek veya sonlandırmak;",
          "kullanım limitleri getirmek;",
          "teknik gereksinimleri güncellemek;",
          "bakım, hukuki, güvenlik, operasyonel veya ürün gerekçeleriyle erişimi askıya almak.",
          "Hukukun izin verdiği ölçüde BMNova; kesinti, gecikme, erişim sorunu veya özellik değişikliklerinden kaynaklanan zararlardan sorumlu değildir.",
        ],
      },
      {
        number: 17,
        title: "Askıya Alma ve Sona Erdirme",
        paragraphs: [
          "Aşağıdaki hallerde erişiminizi derhal veya herhangi bir zamanda askıya alabilir ya da sona erdirebiliriz:",
          "bu Koşullar'ı ihlal etmeniz;",
          "hukuki, güvenlik veya operasyonel risk oluşturmanız;",
          "dolandırıcılık, kötüye kullanım veya yetkisiz faaliyet şüphesi bulunması;",
          "kanunen veya üçüncü taraf platform/sağlayıcı tarafından bunu yapmamızın gerekmesi;",
          "uygulanabildiği ölçüde ödeme yükümlülüklerinin çözümsüz kalması.",
          "Hizmetleri kullanmayı istediğiniz zaman bırakabilir ve varsa yinelenen aboneliğinizi ilgili ödeme akışına uygun şekilde iptal edebilirsiniz.",
          "Sona erme halinde hizmetleri kullanma hakkınız derhal biter. Niteliği gereği sona ermeden sonra da geçerli olması gereken hükümler yürürlükte kalır; buna ödenmesi gereken tutarlar, fikri mülkiyet, feragat beyanları, sorumluluk sınırlamaları, uyuşmazlıklar ve uygulama hükümleri dahildir.",
        ],
      },
      {
        number: 18,
        title: "Sorumluluk Reddi",
        paragraphs: [
          'Uygulanabilir hukukun izin verdiği azami ölçüde, hizmetler "olduğu gibi" ve "mevcut olduğu şekliyle" sunulur.',
          "BMNova, hizmetlerin kesintisiz, hatasız, güvenli veya her amaca uygun olacağını garanti etmez. Hukukun izin verdiği ölçüde BMNova; ticari elverişlilik, belirli bir amaca uygunluk, ihlal etmeme ve doğruluk dahil olmak üzere zımni garantileri reddeder.",
          "Yukarıdakileri sınırlamaksızın BMNova aşağıdakileri garanti etmez:",
          "hizmetlerin ihtiyaçlarınızı veya beklentilerinizi karşılayacağını;",
          "hizmetlerin her zaman erişilebilir, kesintisiz, zamanında, güvenli veya hatasız olacağını;",
          "herhangi bir çıktı, öneri, analiz veya yapay zekâ üretimi sonucun doğru, eksiksiz, güvenilir, hukuka uygun veya belirli bir amaca uygun olacağını;",
          "tüm kusurların mutlaka giderileceğini; veya",
          "hizmetlerin tamamen zararlı bileşenlerden ari olacağını.",
          "Bu bölüm, uygulanabilir tüketici hukuku kapsamında sahip olabileceğiniz ve feragat edilemeyen hakları sınırlamaz.",
        ],
      },
      {
        number: 19,
        title: "Sorumluluğun Sınırlandırılması",
        paragraphs: [
          "Uygulanabilir hukukun izin verdiği azami ölçüde BMNova ve bağlı kişi/kuruluşları, yüklenicileri, lisans verenleri, hizmet sağlayıcıları ve temsilcileri; hizmetleri kullanmanızdan veya kullanamamanızdan kaynaklanan ya da bununla bağlantılı olan dolaylı, arızi, özel, sonuçsal veya cezai zararlardan ya da kâr, gelir, iş, itibar, veri veya fırsat kayıplarından sorumlu olmayacaktır.",
          "Uygulanabilir hukukun izin verdiği azami ölçüde, BMNova'nın hizmetler veya bu Koşullar ile bağlantılı tüm taleplere ilişkin toplam sorumluluğu, talebe yol açan olaydan önceki 12 ay içinde ilgili ücretli hizmet için BMNova'ya ödediğiniz toplam tutarı aşmayacaktır.",
          "Bu Koşullar'da yer alan hiçbir hüküm, hukuken sınırlandırılamayan veya bertaraf edilemeyen sorumluluğu ortadan kaldırmaz veya sınırlandırmaz.",
        ],
      },
      {
        number: 20,
        title: "Hizmetleri Kullanımınızdan Doğan Sorumluluk",
        paragraphs: [
          "Hizmetleri kullanımınızdan, Kullanıcı İçeriğinizden ve bu Koşullar ile yürürlükteki hukuka uyumunuzdan siz sorumlusunuz.",
          "Bir üçüncü tarafın BMNova'ya karşı doğrudan aşağıdakilerden kaynaklanan bir talepte bulunması halinde:",
          "yüklediğiniz veya gönderdiğiniz içerik;",
          "hizmetleri hukuka aykırı şekilde kullanmanız; veya",
          "bu Koşullar'ı ihlal etmeniz ya da üçüncü taraf haklarını ihlal etmeniz,",
          "BMNova'nın maruz kaldığı ve sizin eylemlerinizden kaynaklanan makul zarar, masraf veya giderlerden, hukukun izin verdiği ölçüde sorumlu olmayı kabul edersiniz.",
          "Bir talebin BMNova'nın kendi hukuka aykırı davranışından, ağır ihmalinden veya kasten kusurlu davranışından kaynaklandığı ölçüde bu bölüm uygulanmaz.",
        ],
      },
      {
        number: 21,
        title: "İhracat, Yaptırımlar ve Uyum",
        paragraphs: [
          "Hizmetleri ihracat kontrolü, yaptırımlar veya diğer ticaret mevzuatını ihlal edecek şekilde kullanamazsınız.",
          "Hizmetleri yürürlükteki kısıtlamaları veya yasaları ihlal edecek şekilde kullanmadığınızı beyan edersiniz.",
        ],
      },
      {
        number: 22,
        title: "Gizlilik",
        paragraphs: [
          "Hizmetleri kullanımınız ayrıca kişisel verilerinizi nasıl işlediğimizi açıklayan Gizlilik Politikamız'a tabidir.",
        ],
      },
      {
        number: 23,
        title: "Uygulama Mağazası Şartları",
        paragraphs: [
          "Bir BMNova mobil uygulamasını Apple App Store veya Google Play üzerinden indiriyor ya da kullanıyorsanız şunları kabul edersiniz:",
          "platform kurallarında aksi öngörülmedikçe bu Koşullar sizinle BMNova arasındadır; Apple veya Google ile değildir;",
          "Apple ve Google, kendi koşulları veya yürürlükteki hukuk aksini gerektirmedikçe uygulamanın bakımından veya desteğinden sorumlu değildir;",
          "uygulamayı kullanımınız ilgili uygulama mağazasının kurallarına uygun olmalıdır.",
        ],
      },
      {
        number: 24,
        title: "Uygulanacak Hukuk ve Uyuşmazlıklar",
        paragraphs: [
          "Bu Koşullar, kanunlar ihtilafı kuralları hariç olmak üzere Türkiye Cumhuriyeti hukukuna tabidir; ancak ikamet ettiğiniz ülkedeki zorunlu tüketici hukuku farklı bir koruma sağlıyorsa bu haklar saklıdır.",
          "Bu Koşullar'dan veya hizmetlerden doğan ya da bunlarla bağlantılı uyuşmazlıklarda, uygulanabilir hukukun farklı bir yetki alanı öngördüğü haller saklı kalmak üzere, Ankara Mahkemeleri ve İcra Daireleri yetkilidir.",
          "Tüketici olarak ikamet yerinizde dava açmanıza imkân tanıyan emredici haklarınız varsa, bu haklar saklıdır.",
        ],
      },
      {
        number: 25,
        title: "Bu Koşullardaki Değişiklikler",
        paragraphs: [
          "Bu Koşullar'ı zaman zaman güncelleyebiliriz.",
          'Güncelleme yaptığımızda yukarıdaki "Son güncelleme" tarihini değiştiririz. Esaslı değişikliklerde ayrıca web sitesi, uygulama, e-posta veya ürün arayüzü üzerinden ek bildirim sağlayabiliriz.',
          "Güncellenen Koşullar yürürlüğe girdikten sonra hizmetleri kullanmaya devam etmeniz, revize edilen Koşullar'ı kabul ettiğiniz anlamına gelir.",
        ],
      },
      {
        number: 26,
        title: "Genel Hükümler",
        paragraphs: [
          "Bu Koşullar'ın herhangi bir hükmü geçersiz veya uygulanamaz sayılırsa, kalan hükümler yürürlükte kalmaya devam eder.",
          "Herhangi bir hükmü uygulamamamız, o hükümden feragat ettiğimiz anlamına gelmez.",
          "Önceden yazılı iznimiz olmadan bu Koşullar kapsamındaki hak ve yükümlülüklerinizi devredemezsiniz. Biz ise birleşme, devralma, yeniden yapılanma, malvarlığı devri veya kanun gereği bu Koşullar'ı devredebiliriz.",
          "Bu Koşullar, atıf yoluyla dahil edilen ek ürün koşulları, fiyatlandırma koşulları ve politikalar ile birlikte, hizmetlere ilişkin olarak sizinle BMNova arasındaki anlaşmanın tamamını oluşturur.",
        ],
      },
      {
        number: 27,
        title: "İletişim",
        paragraphs: [
          "Bu Koşullar hakkında sorularınız için:",
          "BMNova",
          "İşleten: Ali Mertcan Karaman",
          "OSTİM OSB Mah. Cevat Dündar Cad. No: 1/1 İç Kapı No: 10",
          "Yenimahalle / Ankara, Türkiye",
          "contact@bmnova.com",
        ],
      },
    ],
  },
};
