import type { TeamMember } from "@websites/shared/types";
import type { Locale } from "@/lib/i18n";

export { type Locale };

export const contentMap = {
  en: {
    meta: {
      homeTitle: "BMNova — Mobile app studio & AI startup",
      description:
        "BMNova is a mobile app studio and consumer-app startup in Ankara. We design, build and ship our own AI apps for iOS and Android.",
      pages: {
        about: { title: "About BMNova — Mobile app studio & startup", description: "BMNova is an independent mobile app studio and consumer-app startup at Ostim Teknokent, Ankara. Meet the studio behind Pali, FitVibe, Haki and the rest." },
        careers: { title: "Careers — BMNova", description: "Join BMNova. We're hiring a Mobile App Growth Expert." },
        blog: { title: "Blog — BMNova", description: "Evidence-based writing on health, productivity, psychology, and building software products." },
        privacy: { title: "Privacy Policy — BMNova", description: "BMNova Privacy Policy. How we collect, use, store, share, and protect personal data." },
        terms: { title: "Terms of Use — BMNova", description: "BMNova Terms of Use. Access and use of our websites, apps, AI features, and services." },
        refund: { title: "Refund Policy — BMNova", description: "BMNova Refund Policy. How refund requests are handled for web and mobile purchases." },
        deletion: { title: "Account & Data Deletion — BMNova", description: "BMNova Account and Data Deletion. How to delete your account and personal data." },
      },
    },
    nav: {
      apps: "Apps",
      studio: "Studio",
      shipLog: "Ship log",
      careers: "Careers",
      getApps: "Get the apps",
      menu: "Toggle menu",
      switchTo: "Türkçe",
      switchLabel: "TR",
    },
    hero: {
      badge: "Mobile app studio & startup · Ankara → worldwide",
      titleLine1: "Tiny studio.",
      titleBig: "Big",
      titleAccent: "apps.",
      sub: "BMNova designs, builds and ships its own AI-powered consumer apps. Five in the stores and the next ones already in the lab.",
      ctaApps: "Explore the apps",
      ctaHiring: "We're hiring",
      nowShowing: "Now showing",
      pickApp: "Pick an app",
      showApp: "Show {name}",
    },
    numbers: {
      heading: "Only real numbers here.",
      note: "From App Store Connect and Play Console, all apps combined",
      apps: { label: "apps built", sub: "4 live · 2 in the lab · 1 archived" },
      downloads: { label: "downloads", sub: "across iOS and Android" },
      ratings: { label: "store ratings", sub: "and {n}+ written reviews" },
      inhouse: { label: "in-house", sub: "design, code, AI, growth" },
      founded: { label: "founded", sub: "Ostim Teknokent, Ankara" },
    },
    apps: {
      eyebrow: "The apps",
      headingStart: "One studio. One obsession: making AI feel",
      headingEm: "useful.",
      sub: "Each one solves a small, daily problem. Each one is designed, built and grown by the same team.",
      status: { live: "Live", review: "In review", lab: "In the lab", archived: "Archived" },
      both: "iOS · Android",
      android: "Android",
      notify: "Notify me",
      open: "Open page →",
      labEyebrow: "In the lab",
      labHeading: "Next ones are in the lab.",
      labSub: "Built in-house and almost out the door. Open one to get a note on launch day.",
      archiveNote: "An earlier experiment. Still on Google Play, no longer in active development.",
    },
    reviews: {
      eyebrow: "Loved by users",
      heading: "Real reviews, straight from the stores.",
      note: "From the App Store and Google Play · drag to browse",
      translated: "translated from Turkish",
      source: { appStore: "App Store", googlePlay: "Google Play" },
      stars: "5 out of 5 stars",
    },
    core: {
      eyebrow: "How we move fast",
      heading: "One core. Seven apps.",
      body: "Every app runs on the same engine: one Flutter codebase, one AI layer, shared onboarding and paywalls, and content we update remotely without shipping a new build.",
      chips: ["Flutter", "AI layer", "dynamic.intyx", "Shared onboarding & paywalls"],
      center: "core",
      hint: "Tap the atom to pause it · tap an app to open it",
    },
    shipLog: {
      eyebrow: "Ship log",
      heading: "Recently shipped.",
      note: "Straight from the app repositories",
    },
    studio: {
      eyebrow: "The studio",
      heading1: "Built in Ankara.",
      heading2: "Shipped everywhere.",
      body: "BMNova is an independent mobile app studio and consumer-app startup: a small team at Ostim Teknokent, shipping our own AI apps worldwide. We use what we build, and we keep improving the ones people keep opening.",
      values: [
        "We ship small and often.",
        "Every app is one we design, build and grow.",
        "AI that does one job well beats AI that does everything.",
      ],
      founder: "Founder",
      yourCard: "Your card could be here.",
      seeRoles: "See open roles →",
    },
    careersCta: {
      eyebrow: "Careers",
      heading: "We're growing. Come grow with us.",
      body: "Small team, big surface area. If you want your work in front of real users this month, not next year, talk to us.",
      openRole: "Open role",
      readRole: "Read the role",
    },
    appPage: {
      allApps: "All apps",
      get: "Get {name}",
      notify: "Notify me at launch",
      earlyAccess: "Get early access",
      liveBoth: "Live on iOS & Android",
      liveAndroid: "Live on Android",
      inReview: "In App Store review",
      inLab: "In the lab · launching soon",
      archived: "Archived · still on Google Play",
      madeIn: "Made in Ankara",
      worksWith: "Works with",
      howItWorks: "How it works",
      whatItDoes: "What {name} does",
      tryIt: "Try it",
      storeListing: "From the store listing",
      storeNote: "Google Play screenshots · scroll sideways",
      reviewsHeading: "What people say about {name}",
      reviewsNote: "From the App Store and Google Play",
      faqHeading: "Questions about {name}",
      moreFrom: "More from BMNova",
      allSeven: "All seven apps →",
      downloadOn: "Download on the",
      getItOn: "Get it on",
      plus: "Plus",
    },
    company: {
      lead: "BMNova (BMNova Innovations) is an independent mobile app studio and consumer-app startup at Ostim Teknokent in Ankara, Turkey, building products for people everywhere. Founded by Ali Mertcan Karaman, the studio designs, builds and grows its own AI-powered apps for iOS and Android, taking each one from the first idea to the stores and staying with it after launch.",
    },
    aboutUs: {
      eyebrow: "Who we are",
      heading: "About BMNova",
      vision: {
        label: "Vision",
        text: "To build a family of AI-powered consumer apps that people open every day, from a small studio in Ankara to users all over the world.",
      },
      mission: {
        label: "Mission",
        text: "To design, build and grow our own products with a compact, highly skilled team: one shared core, honest numbers and AI that does one job well.",
      },
      teamLabel: "The Team",
      thanks: "With thanks to Zeliha Karaman and Büşra Mercan, for believing in this from day one.",
    },
    footer: {
      tagline: "Independent mobile app studio and startup. Ostim Teknokent, Ankara, Turkey.",
      apps: "Apps",
      studio: "Studio",
      legal: "Legal",
      about: "About",
      blog: "Blog",
      shipLog: "Ship log",
      careers: "Careers",
      privacyPolicy: "Privacy Policy",
      termsOfUse: "Terms of Use",
      refundPolicy: "Refund Policy",
      accountDataDeletion: "Account & Data Deletion",
      copyright: "BMNova Innovations",
    },
    privacyPolicy: {
      back: "← bmnova.com",
      lastUpdatedLabel: "Last updated:",
    },
    termsOfUse: {
      back: "← bmnova.com",
      lastUpdatedLabel: "Last updated:",
    },
    refundPolicy: {
      back: "← bmnova.com",
      lastUpdatedLabel: "Last updated:",
    },
    accountDataDeletion: {
      back: "← bmnova.com",
      lastUpdatedLabel: "Last updated:",
    },
    blog: {
      title: "Blog",
      subtitle: "Thoughts on AI, Flutter, and building software.",
      noPosts: "No posts yet. Check back soon.",
      back: "← bmnova.com",
      allPosts: "← All posts",
      minRead: "min read",
      relatedEyebrow: "From the blog",
      relatedHeading: "Related reading",
      fromStudio: "From BMNova",
      learnMore: "Learn more about {name} →",
    },
    careers: {
      title: "Careers",
      subtitle:
        "We're a small team building serious products. If you're sharp, self-directed, and want to work on things that matter — we'd love to hear from you.",
      opening: {
        title: "Mobile App Growth Expert",
        type: "Part-time · Remote",
        summary: "ASO, paid, retention, content",
        description:
          "We're looking for someone who lives and breathes mobile app growth. You'll own acquisition, retention, and monetization strategy across our mobile products — running experiments, analyzing data, and finding the levers that move the numbers. You'll also create the content that fuels that growth: short-form videos, social posts, and store creatives.",
        responsibilitiesLabel: "What you'll do",
        responsibilities: [
          "Drive user acquisition via ASO, paid campaigns, and organic channels",
          "Design and run A/B tests to improve onboarding and retention",
          "Analyze product metrics and translate insights into growth experiments",
          "Create short-form video, social media posts, and App Store / Google Play creatives",
          "Collaborate closely with the engineering and design team",
          "Build and own our mobile marketing playbook from the ground up",
        ],
        niceLabel: "Nice to have",
        nice: [
          "Experience growing a mobile app past 10K+ MAU",
          "Familiarity with Flutter or mobile development workflows",
          "Background in SaaS or AI-powered products",
          "A portfolio of content you made that performed (TikTok, Reels, UGC-style ads)",
        ],
        apply: "Apply via email",
      },
    },
    team: [
      {
        name: "Ali Mertcan Karaman",
        role: "Founder",
        initials: "AK",
        photo: "/team/ali-mertcan-karaman.jpg",
        twitter: "https://x.com/alimertcank?s=21",
        linkedin: "https://www.linkedin.com/in/ali-mertcan-karaman-088582133/",
        background: [
          { place: "Marmara University", years: "2016–2020" },
          { place: "TUSAŞ", years: "2020–2025" },
        ],
      },
    ] satisfies TeamMember[],
  },
  tr: {
    meta: {
      homeTitle: "BMNova — Mobil uygulama stüdyosu ve startup",
      description:
        "BMNova, Ankara merkezli bir mobil uygulama stüdyosu ve tüketici uygulaması startup'ıdır. Kendi yapay zekâ uygulamalarını iOS ve Android için geliştirir.",
      pages: {
        about: { title: "BMNova Hakkında — Mobil uygulama stüdyosu ve startup", description: "BMNova, Ankara Ostim Teknokent'te bağımsız bir mobil uygulama stüdyosu ve tüketici uygulaması startup'ıdır. Pali, FitVibe, Haki ve diğer uygulamaların arkasındaki stüdyo." },
        careers: { title: "Kariyer — BMNova", description: "BMNova'ya katıl. Mobil Uygulama Büyüme Uzmanı arıyoruz." },
        blog: { title: "Blog — BMNova", description: "Sağlık, üretkenlik, psikoloji ve yazılım ürünleri geliştirme üzerine kanıta dayalı yazılar." },
        privacy: { title: "Gizlilik Politikası — BMNova", description: "BMNova Gizlilik Politikası. Kişisel verileri nasıl topladığımız, kullandığımız, sakladığımız, paylaştığımız ve koruduğumuz." },
        terms: { title: "Kullanım Koşulları — BMNova", description: "BMNova Kullanım Koşulları. Web sitelerimizin, uygulamalarımızın, yapay zekâ özelliklerimizin ve hizmetlerimizin kullanımı." },
        refund: { title: "İade Politikası — BMNova", description: "BMNova İade Politikası. Web ve mobil satın alımlarda iade taleplerinin nasıl ele alındığı." },
        deletion: { title: "Hesap ve Veri Silme — BMNova", description: "BMNova Hesap ve Veri Silme. Hesabınızı ve kişisel verilerinizi nasıl silebileceğiniz." },
      },
    },
    nav: {
      apps: "Uygulamalar",
      studio: "Stüdyo",
      shipLog: "Yayın günlüğü",
      careers: "Kariyer",
      getApps: "Uygulamaları indir",
      menu: "Menüyü aç/kapat",
      switchTo: "English",
      switchLabel: "EN",
    },
    hero: {
      badge: "Mobil uygulama stüdyosu ve startup · Ankara → dünya",
      titleLine1: "Küçük stüdyo.",
      titleBig: "Büyük",
      titleAccent: "uygulamalar.",
      sub: "BMNova kendi yapay zekâ destekli tüketici uygulamalarını tasarlar, geliştirir ve yayınlar. Beşi mağazalarda. Sıradakiler çoktan laboratuvarda.",
      ctaApps: "Uygulamaları keşfet",
      ctaHiring: "Ekibe katıl",
      nowShowing: "Şu an",
      pickApp: "Bir uygulama seç",
      showApp: "{name} uygulamasını göster",
    },
    numbers: {
      heading: "Burada sadece gerçek rakamlar var.",
      note: "App Store Connect ve Play Console'dan, tüm uygulamaların toplamı",
      apps: { label: "uygulama", sub: "4 yayında · 2 laboratuvarda · 1 arşivde" },
      downloads: { label: "indirme", sub: "iOS ve Android'de" },
      ratings: { label: "mağaza puanı", sub: "ve {n}+ yazılı yorum" },
      inhouse: { label: "kendi ekibimiz", sub: "tasarım, kod, yapay zekâ, büyüme" },
      founded: { label: "kuruluş", sub: "Ostim Teknokent, Ankara" },
    },
    apps: {
      eyebrow: "Uygulamalar",
      headingStart: "Tek stüdyo. Tek bir tutku: yapay zekâyı",
      headingEm: "işe yarar kılmak.",
      sub: "Her biri küçük, gündelik bir sorunu çözer. Hepsi aynı ekip tarafından tasarlanır, geliştirilir ve büyütülür.",
      status: { live: "Yayında", review: "İncelemede", lab: "Laboratuvarda", archived: "Arşivde" },
      both: "iOS · Android",
      android: "Android",
      notify: "Haber ver",
      open: "Sayfayı aç →",
      labEyebrow: "Laboratuvarda",
      labHeading: "Sıradakiler laboratuvarda.",
      labSub: "Ekipte geliştirildi, kapıdan çıkmak üzere. Çıktığı gün haber almak için sayfasını aç.",
      archiveNote: "Önceki bir denememiz. Google Play'de duruyor, artık aktif geliştirilmiyor.",
    },
    reviews: {
      eyebrow: "Kullanıcılar seviyor",
      heading: "Gerçek yorumlar, doğrudan mağazalardan.",
      note: "App Store ve Google Play'den · sürükleyerek gez",
      translated: "İngilizceden çevrildi",
      source: { appStore: "App Store", googlePlay: "Google Play" },
      stars: "5 üzerinden 5 yıldız",
    },
    core: {
      eyebrow: "Nasıl hızlı ilerliyoruz",
      heading: "Tek çekirdek. Yedi uygulama.",
      body: "Tüm uygulamalar aynı motorla çalışır: tek bir Flutter kod tabanı, tek bir yapay zekâ katmanı, ortak onboarding ve ödeme ekranları ve yeni sürüm yayınlamadan uzaktan güncellediğimiz içerik.",
      chips: ["Flutter", "Yapay zekâ katmanı", "dynamic.intyx", "Ortak onboarding ve paywall"],
      center: "çekirdek",
      hint: "Durdurmak için atoma dokun · açmak için bir uygulamaya dokun",
    },
    shipLog: {
      eyebrow: "Yayın günlüğü",
      heading: "Son yayınlananlar.",
      note: "Doğrudan uygulama repolarından",
    },
    studio: {
      eyebrow: "Stüdyo",
      heading1: "Ankara'da geliştirildi.",
      heading2: "Her yerde yayında.",
      body: "BMNova, bağımsız bir mobil uygulama stüdyosu ve tüketici uygulaması startup'ıdır: Ostim Teknokent'te küçük bir ekip, kendi yapay zekâ uygulamalarını dünyaya yayınlıyor. Geliştirdiklerimizi kendimiz kullanıyor, insanların açmaya devam ettiklerini geliştirmeye devam ediyoruz.",
      values: [
        "Küçük ve sık yayınlarız.",
        "Her uygulamayı kendimiz tasarlar, geliştirir ve büyütürüz.",
        "Tek bir işi iyi yapan yapay zekâ, her şeyi yapmaya çalışandan iyidir.",
      ],
      founder: "Kurucu",
      yourCard: "Senin kartın burada olabilir.",
      seeRoles: "Açık pozisyonlar →",
    },
    careersCta: {
      eyebrow: "Kariyer",
      heading: "Büyüyoruz. Bizimle büyü.",
      body: "Küçük ekip, geniş etki alanı. İşinin seneye değil bu ay gerçek kullanıcılarla buluşmasını istiyorsan bize yaz.",
      openRole: "Açık pozisyon",
      readRole: "İlanı oku",
    },
    appPage: {
      allApps: "Tüm uygulamalar",
      get: "{name} indir",
      notify: "Yayınlanınca haber ver",
      earlyAccess: "Erken erişim al",
      liveBoth: "iOS ve Android'de yayında",
      liveAndroid: "Android'de yayında",
      inReview: "App Store incelemesinde",
      inLab: "Laboratuvarda · yakında",
      archived: "Arşivde · Google Play'de duruyor",
      madeIn: "Ankara'da geliştirildi",
      worksWith: "Uyumlu",
      howItWorks: "Nasıl çalışır",
      whatItDoes: "{name} neler yapar",
      tryIt: "Dene",
      storeListing: "Mağaza sayfasından",
      storeNote: "Google Play ekran görüntüleri · yana kaydır",
      reviewsHeading: "{name} hakkında ne diyorlar",
      reviewsNote: "App Store ve Google Play'den",
      faqHeading: "{name} hakkında sorular",
      moreFrom: "BMNova'dan diğerleri",
      allSeven: "Yedi uygulamanın hepsi →",
      downloadOn: "İndir",
      getItOn: "Şuradan edinin",
      plus: "Plus",
    },
    company: {
      lead: "BMNova (BMNova Innovations), Türkiye'nin Ankara kentindeki Ostim Teknokent'te kurulu, ürünlerini dünyanın her yerine ulaştıran bağımsız bir mobil uygulama stüdyosu ve tüketici uygulaması startup'ıdır. Ali Mertcan Karaman'ın kurduğu stüdyo, iOS ve Android için kendi yapay zekâ uygulamalarını ilk fikirden mağazalara kadar tasarlar, geliştirir ve büyütür; yayınlandıktan sonra da üzerinde çalışmaya devam eder.",
    },
    aboutUs: {
      eyebrow: "Biz kimiz",
      heading: "BMNova Hakkında",
      vision: {
        label: "Vizyon",
        text: "Ankara'daki küçük bir stüdyodan dünyanın dört bir yanındaki kullanıcılara, insanların her gün açtığı yapay zekâ destekli tüketici uygulamalarından oluşan bir aile kurmak.",
      },
      mission: {
        label: "Misyon",
        text: "Küçük ve son derece yetkin bir ekiple kendi ürünlerimizi tasarlamak, geliştirmek ve büyütmek: tek bir ortak çekirdek, dürüst rakamlar ve tek bir işi iyi yapan yapay zekâ.",
      },
      teamLabel: "Ekibimiz",
      thanks: "İlk günden beri inandıkları için Zeliha Karaman ve Büşra Mercan'a teşekkürler.",
    },
    footer: {
      tagline: "Bağımsız mobil uygulama stüdyosu ve startup. Ostim Teknokent, Ankara, Türkiye.",
      apps: "Uygulamalar",
      studio: "Stüdyo",
      legal: "Yasal",
      about: "Hakkımızda",
      blog: "Blog",
      shipLog: "Yayın günlüğü",
      careers: "Kariyer",
      privacyPolicy: "Gizlilik Politikası",
      termsOfUse: "Kullanım Koşulları",
      refundPolicy: "İade Politikası",
      accountDataDeletion: "Hesap ve Veri Silme",
      copyright: "BMNova Innovations",
    },
    privacyPolicy: {
      back: "← bmnova.com",
      lastUpdatedLabel: "Son güncelleme:",
    },
    termsOfUse: {
      back: "← bmnova.com",
      lastUpdatedLabel: "Son güncelleme:",
    },
    refundPolicy: {
      back: "← bmnova.com",
      lastUpdatedLabel: "Son güncelleme:",
    },
    accountDataDeletion: {
      back: "← bmnova.com",
      lastUpdatedLabel: "Son güncelleme:",
    },
    blog: {
      title: "Blog",
      subtitle: "Yapay zeka, Flutter ve yazılım geliştirme üzerine düşünceler.",
      noPosts: "Henüz yazı yok. Yakında tekrar kontrol edin.",
      back: "← bmnova.com",
      allPosts: "← Tüm yazılar",
      minRead: "dk okuma",
      relatedEyebrow: "Blogdan",
      relatedHeading: "İlgili yazılar",
      fromStudio: "BMNova'dan",
      learnMore: "{name} hakkında daha fazlası →",
    },
    careers: {
      title: "Kariyer",
      subtitle:
        "Ciddi ürünler geliştiren küçük bir ekibiz. Keskin, bağımsız çalışabilen ve önemli şeyler üretmek isteyen biri arıyorsak — sizden haber almak isteriz.",
      opening: {
        title: "Mobil Uygulama Büyüme Uzmanı",
        type: "Yarı zamanlı · Uzaktan",
        summary: "ASO, ücretli kampanyalar, elde tutma, içerik",
        description:
          "Mobil uygulama büyümesini içselleştirmiş birini arıyoruz. Mobil ürünlerimizde edinim, elde tutma ve monetizasyon stratejisini üstleneceksiniz — deneyler yapacak, verileri analiz edecek ve sayıları hareket ettiren kaldıraçları bulacaksınız. Bu büyümeyi besleyen içerikleri de siz üreteceksiniz: kısa videolar, sosyal medya paylaşımları ve mağaza görselleri.",
        responsibilitiesLabel: "Ne yapacaksınız",
        responsibilities: [
          "ASO, ücretli kampanyalar ve organik kanallar aracılığıyla kullanıcı edinimini yönetin",
          "Onboarding ve elde tutmayı iyileştirmek için A/B testleri tasarlayın ve yürütün",
          "Ürün metriklerini analiz edin ve içgörüleri büyüme deneylerine dönüştürün",
          "Kısa video, sosyal medya paylaşımları ve App Store / Google Play görselleri üretin",
          "Mühendislik ve tasarım ekibiyle yakın işbirliği yapın",
          "Mobil pazarlama playbook'umuzu sıfırdan oluşturun",
        ],
        niceLabel: "Artı değer",
        nice: [
          "10K+ MAU'ya ulaşmış bir mobil uygulamayı büyütme deneyimi",
          "Flutter veya mobil geliştirme süreçlerine aşinalık",
          "SaaS veya yapay zeka ürünleri geçmişi",
          "Ürettiğiniz ve iyi performans göstermiş içeriklerden bir portfolyo (TikTok, Reels, UGC tarzı reklamlar)",
        ],
        apply: "E-posta ile başvur",
      },
    },
    team: [
      {
        name: "Ali Mertcan Karaman",
        role: "Kurucu",
        initials: "AK",
        photo: "/team/ali-mertcan-karaman.jpg",
        twitter: "https://x.com/alimertcank?s=21",
        linkedin: "https://www.linkedin.com/in/ali-mertcan-karaman-088582133/",
        background: [
          { place: "Marmara Üniversitesi", years: "2016–2020" },
          { place: "TUSAŞ", years: "2020–2025" },
        ],
      },
    ] satisfies TeamMember[],
  },
};

/** Fills {placeholders} in a content string. */
export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? `{${key}}`));
}
